# Generated by Django 5.0.14 on 2026-08-08 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('abstract_text', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('presentation_type', models.CharField(choices=[('PAPER', 'Paper'), ('POSTER', 'Poster')], default='PAPER', max_length=10)),
                ('paper_file', models.FileField(blank=True, null=True, upload_to='papers/')),
                ('poster_file', models.FileField(blank=True, null=True, upload_to='posters/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('REVISION_REQUIRED', 'Revision Required'), ('CAMERA_READY', 'Camera Ready')], default='SUBMITTED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='conferences.conference')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
